actor_hidden_layers: 2
algo: ppo
critic_hidden_layers: 1
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 11
max_episodes: 3000
num_frame: 3
render: false
run_dir: map11_use_dist_self_play_shuffle_pos_[actor]2layers_[frames]3
save_interval: 100
seed: 1
shuffle_map: false
shuffle_place: true
train_by_win: false
use_cnn: false
