actor_hidden_layers: 1
algo: ppo
critic_hidden_layers: 1
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 9
max_episodes: 3000
num_frame: 1
render: false
run_dir: map9_use_dist_self_play
save_interval: 100
seed: 1
shuffle_map: false
train_by_win: false
use_cnn: false
