actor_hidden_layers: 1
algo: ppo
buffer_capacity: 3000
critic_hidden_layers: 1
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 1
max_episodes: 3000
num_frame: 1
render: false
run_dir: shuffle_use_dist_self_play_shuffle_pos_[CNN]_big_batch_use_cross
save_interval: 100
seed: 1
shuffle_map: true
shuffle_place: true
train_by_win: false
use_cnn: true
use_step_dist: false
